name: Deploy Argus backend as a containerized Azure Function

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      
      # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository
        
        # Step 3: Log in to Azure Container Registry
      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Step 3: Build and push the Docker image for the argus frontend to ACR
      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/argus-backend
        run: |
          docker build -f docker/backend.Dockerfile -t ${{ secrets.ACR_NAME }}/argus_backend:latest .
          docker push ${{ secrets.ACR_NAME }}/argus_backend:latest
